server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    #tomcat 默认的线程数量默认为 200 可自定义
    max-threads: 200
    #tomcat 启动最小线程数量 默认为10 可自定义
    min-spare-threads: 15
# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    prefix: classpath:/templates/thymeleaf/
    servlet:
      content-type: text/html; charset=utf-8
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    #配置开发环境与生产环境的数据库
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      max-file-size:  50MB
      max-request-size:  50MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
      additional-paths: resources/**,static/**,templates/**
  # springmvc配置
  mvc:
    static-path-pattern: /static/**
#mybatis
#mappers 多个接口时逗号隔开
mybatis:
  type-aliases-package: com.nextone.mapper
  mapper-locations: classpath:mapper/*.xml
# 日志配置
logging:
  level:com.nextone: debug
mapper:
  mappers:  com.nextone.framework.MyMapper
  not-empty: false
  identity:  MYSQL



